services:
  orders:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    depends_on:
      rabbitmq:
          condition: service_healthy
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ..
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 30s
      timeout: 10s
      retries: 5