services:
  orders:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
      STRIPE_SECRET_KEY: your_stripe_secret_key
      STRIPE_PUBLISHABLE_KEY: your_stripe_publishable_key
    depends_on:
      - rabbitmq
    ports:
      - 80:80
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest