services:
  orders:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest