stages:
  - test
  - build
  - scan
  - push
  - staging

variables:
  SERVICE: "notes"
  DS_EXCLUDED_ANALYZERS: "gemnasium,gemnasium-python"
  ECR_REGISTRY: "211125709264.dkr.ecr.ap-southeast-1.amazonaws.com/${SERVICE}"
  IMAGE: "$CI_REGISTRY_IMAGE:$SERVICE-$CI_COMMIT_REF_SLUG"
  SERVICE_NAME: notes-ecs-staging
  TASK_DEFINITION_NAME: notes-ecs-task-staging

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

notes-tests:
 stage: test
 image: maven:3.6.3-openjdk-17
 before_script:
   - cd ./apps/notes
 script:
   - mvn test
 allow_failure: false
 artifacts:
   when: always
   paths:
     - coverage/

# Build Docker Image
notes-build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    - apk add --no-cache git
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - cd ./apps/${SERVICE}
    - git fetch --tags
    - LATEST_TAG=$(git tag --list "${SERVICE}-v[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n 1)
    - SEMVER=$(echo "$LATEST_TAG" | sed "s/${SERVICE}-//")
    - VERSION="${SEMVER}-${CI_COMMIT_SHORT_SHA}"
    - echo "VERSION=${VERSION}" >> build.env

    - docker build -t $IMAGE .
    - docker push $IMAGE
  artifacts:
    reports:
      dotenv: ./apps/${SERVICE}/build.env
  # only:
  #   - tags

container_scanning:
  stage: scan
  variables:
    CS_IMAGE: "$IMAGE"
    CS_DOCKERFILE_PATH: "./apps/notes/Dockerfile"
  dependencies:
    - notes-build

notes-push:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: push
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install awscli
    - aws --version
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $IMAGE
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 211125709264.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker tag $IMAGE ${ECR_REGISTRY}:${VERSION}
    - docker tag $IMAGE ${ECR_REGISTRY}:latest
    - docker push ${ECR_REGISTRY}:${VERSION}
    - docker push ${ECR_REGISTRY}:latest
  dependencies:
    - notes-build

ecs-staging:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: staging
  before_script:
    - apk add --no-cache python3 jq py3-pip
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - $(aws ecr get-login --no-include-email --region "${AWS_DEFAULT_REGION}")
  script:
    - echo ${ECR_REGISTRY}:${VERSION}
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${AWS_DEFAULT_REGION}")
    - echo $TASK_DEFINITION
    - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE_ECR "${ECR_REGISTRY}:${VERSION}" '.taskDefinition.containerDefinitions[0].image = $IMAGE_ECR | .taskDefinition.containerDefinitions[0]')
    - CPU=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.cpu')
    - MEMORY=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.memory')
    - REQUIRES_COMPATIBILITIES=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.requiresCompatibilities')
    - TASK_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.taskRoleArn')
    - EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.executionRoleArn')
    - NETWORK_MODE=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.networkMode')
    - RUNTIME_PLATFORM=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.runtimePlatform')
    - echo $NEW_CONTAINER_DEFINITION
    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --cpu "${CPU}" --memory "${MEMORY}" --requires-compatibilities "${REQUIRES_COMPATIBILITIES}" --task-role-arn "${TASK_ROLE_ARN}" --execution-role-arn "${EXECUTION_ROLE_ARN}" --network-mode "${NETWORK_MODE}" --runtime-platform "${RUNTIME_PLATFORM}"
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${STAGING_CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"
  only:
    - main
  dependencies:
    - notes-build


