stages:
  - Test

order-unit-tests:
  stage: Test
  image: node:20-slim
  before_script:
    - cd ./apps/orders
    - npm install
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - coverage/
  variables:
    STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY