stages:
  - test
  - build
  - scan
  - push
  - staging
  - notification
  - production

variables:
  SERVICE: "verify"
  DS_EXCLUDED_ANALYZERS: "gemnasium,gemnasium-maven"
  ECR_REGISTRY: "211125709264.dkr.ecr.ap-southeast-1.amazonaws.com/${SERVICE}"
  IMAGE: "$CI_REGISTRY_IMAGE:$SERVICE-$CI_COMMIT_REF_SLUG"
  SERVICE_NAME: verify-ecs-staging-2
  TASK_DEFINITION_NAME: verify-ecs-task-staging
  SERVICE_NAME_PROD: verify-ecs-lb-production
  TASK_DEFINITION_NAME_PROD: verify-ecs-task-production

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

flake8:
  stage: test
  image: python:3.12-slim
  before_script:
    - cd ./apps/${SERVICE}
    - python -V
    - python -m pip install flake8
  script:
    - flake8 --ignore=E501 ./app.py | tee flake8_report.txt
  artifacts:
    when: on_failure
    paths:
      - flake8_report.txt

pylint:
  stage: test
  image: python:3.12-slim
  before_script:
    - cd ./apps/${SERVICE}
    - python -V
    - python -m pip install -r requirements.txt
    - python -m pip install pylint
  script:
    - pylint --fail-under=6 ./app.py | tee pylint_report.txt
  artifacts:
    when: always
    paths:
      - pylint_report.txt

# Build Docker Image
verify-build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    - apk add --no-cache git
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - cd ./apps/${SERVICE}
    - git fetch --tags
    - LATEST_TAG=$(git tag --list "${SERVICE}-v[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n 1)
    - SEMVER=$(echo "$LATEST_TAG" | sed "s/${SERVICE}-//")
    - VERSION="${SEMVER}-${CI_COMMIT_SHORT_SHA}"
    - echo "VERSION=${VERSION}" >> build.env
    - docker build -t $IMAGE .
    - docker push $IMAGE
  artifacts:
    reports:
      dotenv: ./apps/${SERVICE}/build.env
  # only:
  #   - tags

container_scanning:
  stage: scan
  variables:
    CS_IMAGE: "$IMAGE"
    CS_DOCKERFILE_PATH: "./apps/verify/Dockerfile"
  dependencies:
    - verify-build

verify-push:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: push
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install awscli
    - aws --version
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $IMAGE
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 211125709264.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker tag $IMAGE ${ECR_REGISTRY}:${VERSION}
    - docker tag $IMAGE ${ECR_REGISTRY}:latest
    - docker push ${ECR_REGISTRY}:${VERSION}
    - docker push ${ECR_REGISTRY}:latest
    - echo ${VERSION}
  dependencies:
    - verify-build

ecs-staging:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: staging
  before_script:
    - apk add --no-cache python3 jq py3-pip 
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - $(aws ecr get-login --no-include-email --region "${AWS_DEFAULT_REGION}")
  script:
    - echo ${ECR_REGISTRY}:${VERSION}
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${AWS_DEFAULT_REGION}")
    - echo $TASK_DEFINITION
    - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE_ECR "${ECR_REGISTRY}:${VERSION}" '.taskDefinition.containerDefinitions[0].image = $IMAGE_ECR | .taskDefinition.containerDefinitions[0]')
    - CPU=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.cpu')
    - MEMORY=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.memory')
    - REQUIRES_COMPATIBILITIES=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.requiresCompatibilities')
    - TASK_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.taskRoleArn')
    - EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.executionRoleArn')
    - NETWORK_MODE=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.networkMode')
    - RUNTIME_PLATFORM=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.runtimePlatform')
    - echo $NEW_CONTAINER_DEFINITION
    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --cpu "${CPU}" --memory "${MEMORY}" --requires-compatibilities "${REQUIRES_COMPATIBILITIES}" --task-role-arn "${TASK_ROLE_ARN}" --execution-role-arn "${EXECUTION_ROLE_ARN}" --network-mode "${NETWORK_MODE}" --runtime-platform "${RUNTIME_PLATFORM}"
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${STAGING_CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"
  only:
    - main
  dependencies:
    - verify-build

success:
  stage: notification
  script:
    - echo "Pipeline passed, no notification sent."
  when: on_success
  allow_failure: true  

failure_notification:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $VERIFY_WEBHOOK_URL
  when: on_failure
  allow_failure: true 


ecs-production:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: production
  before_script:
    - apk add --no-cache python3 jq py3-pip
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - $(aws ecr get-login --no-include-email --region "${AWS_DEFAULT_REGION}")
  script:
    - echo ${ECR_REGISTRY}:${VERSION}
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME_PROD" --region "${AWS_DEFAULT_REGION}")
    - echo $TASK_DEFINITION
    - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE_ECR "${ECR_REGISTRY}:${VERSION}" '.taskDefinition.containerDefinitions[0].image = $IMAGE_ECR | .taskDefinition.containerDefinitions[0]')
    - CPU=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.cpu')
    - MEMORY=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.memory')
    - REQUIRES_COMPATIBILITIES=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.requiresCompatibilities')
    - TASK_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.taskRoleArn')
    - EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.executionRoleArn')
    - NETWORK_MODE=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.networkMode')
    - RUNTIME_PLATFORM=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.runtimePlatform')
    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${TASK_DEFINITION_NAME_PROD}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --cpu "${CPU}" --memory "${MEMORY}" --requires-compatibilities "${REQUIRES_COMPATIBILITIES}" --task-role-arn "${TASK_ROLE_ARN}" --execution-role-arn "${EXECUTION_ROLE_ARN}" --network-mode "${NETWORK_MODE}" --runtime-platform "${RUNTIME_PLATFORM}"
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${PRODUCTION_CLUSTER_NAME}" --service "${SERVICE_NAME_PROD}"  --task-definition "${TASK_DEFINITION_NAME_PROD}"
    - echo "Finish updating Task:${TASK_DEFINITION_NAME_PROD} Service:${SERVICE_NAME_PROD} Cluster:${PRODUCTION_CLUSTER_NAME} with image:${ECR_REGISTRY}:${VERSION}"
  dependencies:
    - verify-build
  when: manual
  allow_failure: true
  needs: []